ignored:
- DL3018 # warning: Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
- DL3059 # info: Multiple consecutive `RUN` instructions. Consider consolidation.
- DL3006 # warning: Always tag the version of an image explicitly
- SC2086 # info: Double quote to prevent globbing and word splitting.

