ignored:
- DL3018 # warning: Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
- DL3059 # info: Multiple consecutive `RUN` instructions. Consider consolidation.
- SC2086 # info: Double quote to prevent globbing and word splitting.
- SC2016 # info: Expressions don't expand in single quotes, use double quotes for that.
