name: php 8.2 Fitness Functions
  
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '15 10 * * *' # each day at 10:15 UTC


jobs:
  configured-alpine-is-latest-version:
    name: "Ensure that Alpine 3.18 is the latest alpine version"
    env:
      LATEST_ALPINE_RELEASE: "3.18.5"    
    runs-on: ubuntu-latest
    steps:
      -  name: Execute
         run: >
             docker run --pull always --rm alpine:3.18 cat /etc/os-release | grep $LATEST_ALPINE_RELEASE

  php82-is-not-the-default-php-on-edge:
    name: "We need to symlink php82 until php 8.2 is the default php"
    runs-on: ubuntu-latest
    steps:
      -  name: Execute
         run: >
             ! docker run --pull always --rm alpine:3.18 sh -c 'apk -U add php82 && php -v'

  packages-not-available-on-alpine-for-release-8-2:
    name: Package not available on alpine for php 8.2 in community, yet
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - php82-pecl-grpc
          - php82-pecl-pcov
    steps:
      -   name: Execute
          run: "! docker run --pull always --rm alpine:3.18 apk --no-cache search ${{ matrix.package }} | grep ${{ matrix.package }}"
