name: php 8.4 Fitness Functions
  
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '15 10 * * *' # each day at 10:15 UTC


jobs:
  configured-alpine-is-latest-version:
    name: "Ensure that Alpine 3.21 is the latest alpine version"
    env:
      LATEST_ALPINE_RELEASE: "3.21.3"    
    runs-on: ubuntu-latest
    steps:
      -  name: Execute
         run: >
             docker run --pull always --rm alpine:3.21 cat /etc/os-release | grep $LATEST_ALPINE_RELEASE

  php83-is-not-the-default-php-on-edge:
    name: "We need to symlink php84 until php 8.4 is the default php"
    runs-on: ubuntu-latest
    steps:
      -  name: Execute
         run: >
             ! docker run --rm alpine:3.21 sh -c 'apk add -U php84 && php -v'
