name: php 8.5 Fitness Functions

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '15 10 * * *' # each day at 10:15 UTC


jobs:
  configured-alpine-is-latest-version:
    name: "Ensure that Alpine 3.24 is the latest alpine version"
    env:
      LATEST_ALPINE_RELEASE: "3.24.1"
    runs-on: ubuntu-latest
    steps:
      -  name: Execute
         run: >
             docker run --pull always --rm alpine:3.24 cat /etc/os-release | grep $LATEST_ALPINE_RELEASE

  php85-is-not-the-default-php-on-edge:
    name: "We need to symlink php85 until php 8.5 is the default php"
    runs-on: ubuntu-latest
    steps:
      -  name: Execute
         run: >
             ! docker run --pull always --rm alpine:3.24 sh -c 'apk add -U php85 && php -v'
