name: php 8.3 Fitness Functions
  
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '15 10 * * *' # each day at 10:15 UTC


jobs:
  configured-alpine-is-latest-version:
    name: "Ensure that Alpine 3.20 is the latest alpine version"
    env:
      LATEST_ALPINE_RELEASE: "3.20.2"    
    runs-on: ubuntu-latest
    steps:
      -  name: Execute
         run: >
             docker run --pull always --rm alpine:3.20 cat /etc/os-release | grep $LATEST_ALPINE_RELEASE
