name: php 8.4 Fitness Functions
  
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '15 10 * * *' # each day at 10:15 UTC


jobs:
  php83-is-not-the-default-php-on-edge:
    name: "We need to symlink php84 until php 8.4 is the default php"
    runs-on: ubuntu-latest
    steps:
      -  name: Execute
         run: >
             ! docker run --rm alpine:edge sh -c 'apk add -U php84 --repository https://dl-cdn.alpinelinux.org/alpine/edge/testing/ && php -v'

  packages-not-available-on-alpine-for-community-release-8-4:
    name: Package not available on alpine for php 8.4 in community, yet
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - php84
          - php84-pecl-amqp
    steps:
      -   name: Execute
          run: "! docker run --rm alpine:edge apk --no-cache search ${{ matrix.package }} | grep ${{ matrix.package }}"

  packages-not-available-on-alpine-testing-for-release-8-4:
    name: Package not available on alpine for php 8.4 in testing, yet
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - php84-pecl-amqp
    steps:
      -   name: Execute
          run: "! docker run --rm alpine:edge apk --no-cache search --repository https://dl-cdn.alpinelinux.org/alpine/edge/testing/ ${{ matrix.package }}  | grep ${{ matrix.package }}"
