name: php 8.1 Fitness Functions
  
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '15 10 * * *' # each day at 10:15 UTC

jobs:
  configured-release-8-1-alpine-is-latest-version:
    name: "Ensure that Alpine is the latest alpine version for release 8.1"
    env:
      LATEST_ALPINE_RELEASE: "3.19.7"    
    runs-on: ubuntu-latest
    steps:
      -  name: Execute
         run: >
             docker run --pull always --rm alpine:3.19 cat /etc/os-release | grep $LATEST_ALPINE_RELEASE
